### ISSUE TITLE
Use logging instead of print

### ISSUE THREAD

**Issue by alchemyst** [DominicKafka/Quad8-FEM#3]
Print statements scattered throughout your code are a sign that you are doing something wrong. Use the [logging module](https://docs.python.org/2/howto/logging.html#logging-basic-tutorial) for output. At first, don't worry if it's not formatted to your liking, the advantages are huge.

**Comment by DominicKafka** [comment]
Good Day Mr. Sandrock

Yes, I use the print statements to compare what the Matlab code is doing at
a point to what the converted code is doing at the same point. That way I
can see where the problem lies. I then often just comment out the
statements when I no longer need them, but leave them in there just in case
I need to check that variable again.

I realize now though that this is not the best solution. I had a long
meeting with Mrs. Inglis on Friday about the plans for testing and how that
is meant to work. She has suggested I start with the functions within the
main loop, separate them and write appropriate tests for them. I shall be
working on that hopefully very soon.

Regards,
Dominic
